Repository appventure-nush/nush-link, pull requests merged in 2020-11, with the labels that each got.

#1 project-design
  docs/project_design.md
  docs/project_goal.md
Labels: documentation

#2 project-documentation
  README.md
Labels: documentation

#6 rename project-technology.md to project-readings.md
  docs/project_readings.md
Labels: documentation

#12 Removing sequelize for mysql
  .gitignore
  server/.env
  server/package-lock.json
  server/package.json
  server/src/config/database.ts
  server/src/config/index.ts
  server/src/index.js
  server/src/index.ts
  server/src/routes/api/shorten
  server/tsconfig.json
  server/yarn.lock
Labels: backend

#13 Editing App.css and App.tsx to match design
  front-end/react-proj/src/App.css
  front-end/react-proj/src/App.tsx
  front-end/react-proj/src/components/Header.tsx
  front-end/react-proj/src/sprites/background-image.svg
  front-end/react-proj/src/sprites/school-bg.png
Labels: frontend

#14 Removing extra directory react-proj and small edits to the styling
  front-end/.gitignore
  front-end/README.md
  front-end/package-lock.json
  front-end/package.json
  front-end/public/favicon.ico
  front-end/public/index.html
  front-end/public/logo192.png
  front-end/public/logo512.png
  front-end/public/manifest.json
  front-end/public/robots.txt
  front-end/react-proj/src/App.css
  front-end/react-proj/src/App.tsx
  front-end/react-proj/src/components/Header.tsx
  front-end/src/App.css
  front-end/src/App.test.tsx
  front-end/src/App.tsx
  front-end/src/components/LogoCircle.tsx
  front-end/src/index.tsx
  front-end/src/react-app-env.d.ts
  front-end/src/reportWebVitals.ts
  front-end/src/scss/style.scss
  front-end/src/setupTests.ts
  front-end/src/sprites/appventure-logo.svg
  front-end/src/sprites/background-image.svg
  front-end/src/sprites/nushlink-logo.svg
  front-end/src/sprites/nushlink-logo_g.svg
  front-end/src/sprites/nushlink-logo_w.svg
  front-end/src/sprites/school-bg.png
  front-end/tsconfig.json
Labels: frontend
